services:
  web:
    build: .
    container_name: voyage-backend-app
    env_file:
      - .env
    environment:
      - FLASK_APP=backend.wsgi:app
    network_mode: host
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 backend.wsgi:app

  cron-worker:
    build: .
    container_name: voyage-cron-worker
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
    command: ["/app/worker.sh"]